### PR TITLE
feat(formula): align to template formula; add ci

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [x] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES

### Describe the changes you're proposing

Following IntelliJ blueprint (sed replace),  align this formula to template-formula and add Travis.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
MacOS trace
```
local:
----------
          ID: rubymine-macos-app-clean-files
    Function: file.absent
        Name: /tmp/jetbrains/rubymine
      Result: True
     Comment: Removed directory /tmp/jetbrains/rubymine
     Started: 19:46:38.832785
    Duration: 18.308 ms
     Changes:   
              ----------
              removed:
                  /tmp/jetbrains/rubymine
----------
          ID: rubymine-macos-app-clean-files
    Function: file.absent
        Name: /Applications/Rubymine.app
      Result: True
     Comment: Removed directory /Applications/Rubymine.app
     Started: 19:46:38.851347
    Duration: 427.813 ms
     Changes:   
              ----------
              removed:
                  /Applications/Rubymine.app
----------
          ID: rubymine-config-clean-file-absent
    Function: file.absent
        Name: /tmp/dummy_list_item
      Result: True
     Comment: File /tmp/dummy_list_item is not present
     Started: 19:46:39.279386
    Duration: 0.351 ms
     Changes:   
----------
          ID: rubymine-config-clean-file-absent
    Function: file.absent
        Name: /etc/defaults/rubymine.sh
      Result: True
     Comment: Removed file /etc/defaults/rubymine.sh
     Started: 19:46:39.279893
    Duration: 0.42 ms
     Changes:   
              ----------
              removed:
                  /etc/defaults/rubymine.sh
----------
          ID: rubymine-config-clean-file-absent
    Function: file.absent
        Name: /Users/nmcloughlin/Desktop/Rubymine
      Result: True
     Comment: Removed file /Users/nmcloughlin/Desktop/Rubymine
     Started: 19:46:39.280473
    Duration: 0.429 ms
     Changes:   
              ----------
              removed:
                  /Users/nmcloughlin/Desktop/Rubymine
----------
          ID: rubymine-macos-app-install-curl
    Function: file.directory
        Name: /tmp/jetbrains/rubymine
      Result: True
     Comment: Directory /tmp/jetbrains/rubymine updated
     Started: 19:46:39.281006
    Duration: 1.397 ms
     Changes:   
              ----------
              /tmp/jetbrains/rubymine:
                  New Dir
----------
          ID: rubymine-macos-app-install-curl
    Function: pkg.installed
        Name: curl
      Result: True
     Comment: All specified packages are already installed
     Started: 19:46:43.767648
    Duration: 12828.746 ms
     Changes:   
----------
          ID: rubymine-macos-app-install-curl
    Function: cmd.run
        Name: curl -Lo /tmp/jetbrains/rubymine/rubymine-2020.1 https://download.jetbrains.com/ruby/RubyMine-2020.1.dmg
      Result: True
     Comment: Command "curl -Lo /tmp/jetbrains/rubymine/rubymine-2020.1 https://download.jetbrains.com/ruby/RubyMine-2020.1.dmg" run
     Started: 19:46:56.600249
    Duration: 824145.823 ms
     Changes:   
              ----------
              pid:
                  49874
              retcode:
                  0
              stderr:
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                   Dload  Upload   Total   Spent    Left  Speed
                  
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                  100   138  100   138    0     0    213      0 --:--:-- --:--:-- --:--:--   213
                  100   138  100   138    0     0    213      0 --:--:-- --:--:-- --:--:--   213
                  
                    0  350M    0 64701    0     0  46643      0  2:11:10  0:00:01  2:11:09 46643
                    0  350M    0  399k    0     0   167k      0  0:35:46  0:00:02  0:35:44  335k
        <<<CUT>>>>>

                   99  350M   99  348M    0     0   434k      0  0:13:44  0:13:41  0:00:03  296k
                   99  350M   99  349M    0     0   434k      0  0:13:44  0:13:42  0:00:02  342k
                   99  350M   99  349M    0     0   434k      0  0:13:44  0:13:43  0:00:01  417k
                  100  350M  100  350M    0     0   435k      0  0:13:44  0:13:44 --:--:--  448k
              stdout:
----------
          ID: rubymine-macos-app-install-checksum
    Function: module.run
        Name: file.check_hash
      Result: True
     Comment: onlyif condition is false
     Started: 20:00:40.748764
    Duration: 810.291 ms
     Changes:   
----------
          ID: rubymine-macos-app-install-checksum
    Function: file.absent
        Name: /tmp/jetbrains/rubymine/rubymine-2020.1
      Result: True
     Comment: State was not run because onfail req did not change
     Started: 20:00:41.559844
    Duration: 0.004 ms
     Changes:   
----------
          ID: rubymine-macos-app-install-macpackage
    Function: macpackage.installed
        Name: /tmp/jetbrains/rubymine/rubymine-2020.1
      Result: True
     Comment: RubyMine.app installed
     Started: 20:00:41.560074
    Duration: 18657.429 ms
     Changes:   
              ----------
              installed:
                  - RubyMine.app
----------
          ID: rubymine-macos-app-install-macpackage
    Function: file.managed
        Name: /tmp/mac_shortcut.sh
      Result: True
     Comment: File /tmp/mac_shortcut.sh is in the correct state
     Started: 20:01:00.217910
    Duration: 52.514 ms
     Changes:   
----------
          ID: rubymine-macos-app-install-macpackage
    Function: cmd.run
        Name: /tmp/mac_shortcut.sh
      Result: True
     Comment: Command "/tmp/mac_shortcut.sh" run
     Started: 20:01:00.271099
    Duration: 1336.903 ms
     Changes:   
              ----------
              pid:
                  51526
              retcode:
                  0
              stderr:
              stdout:
                  alias file RubyMine of folder Desktop of folder nmcloughlin of folder Users of startup disk
----------
          ID: rubymine-config-file-file-managed-environ_file
    Function: file.managed
        Name: /etc/defaults/rubymine.sh
      Result: True
     Comment: File /etc/defaults/rubymine.sh updated
     Started: 20:01:01.608718
    Duration: 1795.887 ms
     Changes:   
              ----------
              diff:
                  New file
              group:
                  nmcloughlin
              mode:
                  0644
              user:
                  nmcloughlin

Summary for local
-------------
Succeeded: 14 (changed=9)
Failed:     0
```

**Comment by myii** [comment]
* Checked using https://github.com/myii/ssf-formula/pull/182

---

@noelmcloughlin Thank you so much for making it so easy!  I literally didn't change a _single_ thing -- it was ready to go.  Kudos!

**Comment by noelmcloughlin** [comment]
> it was ready to go

Good and cool - all the JetBrains formulas should be ready then as same commits were applied.

**Comment by myii** [comment]
@noelmcloughlin Good to hear.  It still takes me a little while getting all of the configurations into the `ssf-formula`, so I'll still be clearing these over a number of days.  Thank you for your patience.

**Pull request merged**
